"""empty message

Revision ID: d94aa24fed63
Revises: 2fabdd07444c
Create Date: 2023-08-10 20:30:48.439668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94aa24fed63'
down_revision: Union[str, None] = '2fabdd07444c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('readme_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crates_author'), 'crates', ['author'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crate_id', sa.Integer(), nullable=True),
    sa.Column('dependency', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_crate_id'), 'dependencies', ['crate_id'], unique=False)
    op.create_index(op.f('ix_dependencies_dependency'), 'dependencies', ['dependency'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crate_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_crate_id'), 'tags', ['crate_id'], unique=False)
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('users_to_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crate_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uploader', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_crate_id'), 'versions', ['crate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versions_crate_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_table('users_to_roles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.drop_index(op.f('ix_tags_crate_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_dependencies_dependency'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_crate_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_crates_author'), table_name='crates')
    op.drop_table('crates')
    # ### end Alembic commands ###
